---
kind: pipeline
name: default

steps:
- name: lint
  image: archlinux/base:latest
  commands:
    - pacman -Sy --noconfirm git make shellcheck vim
    - make
    - shellcheck ~/.bashrc
    - shellcheck ~/.bash_profile